const $=s=>document.querySelector(s),state={seller:localStorage.getItem('timwin.jph.seller')||'',base:[],history:[],cadencia:null};
const fallbackQuestions={manutencao:'quando surge uma intervenção elétrica ou de automação que exige apoio externo, como vocês decidem com quem buscar ajuda?',engenharia:'quando vocês estudam uma melhoria ou novo projeto elétrico/automação, em que momento costumam envolver empresas externas?',suprimentos:'quando uma área técnica precisa de um novo fornecedor de automação ou serviços elétricos, como esse novo fornecedor normalmente entra no processo de vocês?',direcao:'quando vocês identificam uma melhoria elétrica ou de automação que pode impactar a operação, o que normalmente determina se ela vira prioridade?',ssma:'quando Segurança identifica uma necessidade que exige adequação elétrica ou de automação, como isso normalmente é encaminhado para Engenharia ou Manutenção?'};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
async function api(url,opts){const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw Error(d.error||'Falha na integração');return d}
async function loadHistory(){const d=await api('/api/history');state.history=d.values||[]}
function events(id){return state.history.slice(1).filter(r=>r[3]===id)}
function row(c,evento,data={}){return api('/api/history',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({evento_id:crypto.randomUUID(),data_hora:new Date().toISOString(),vendedor:state.seller,id_contato:c.id_contato,nome:c.contato,empresa:c.empresa,persona:c.persona||'',evento,etapa:data.etapa||'',assunto:data.assunto||'',texto:data.texto||'',resposta_prospect:data.resposta||'',proximo_passo:data.proximo||'',origem:'cloudflare-pages',versao:'cloud-v1'})})}
function personaData(id){return state.cadencia?.personas?.find(p=>p.id===id)||{id,nome:id,emails:[]}}
function stageFor(c){const sent=events(c.id_contato).filter(e=>e[7]==='email_enviado').map(e=>Number(e[8])||0);return Math.min((sent.length?Math.max(...sent)+1:1),4)}
function hasResponse(c){return events(c.id_contato).some(e=>e[7]==='resposta_recebida')}
function makeEmail(c,info,stage){const p=personaData(c.persona),e=p.emails?.find(x=>x.etapa===stage)||p.emails?.[stage-1];if(!e)return null;return{subject:e.assunto.replaceAll('{{empresa}}',c.empresa),body:e.corpo.replaceAll('{{nome}}',c.contato).replaceAll('{{empresa}}',c.empresa).replaceAll('{{vendedor}}',state.seller).replaceAll('{{info_personalizada}}',info)}}
function normalize(x){return{id_contato:x.id_contato||x[0],contato:x.contato||x.nome||x[3],empresa:x.empresa||x[1],cargo_original:x.cargo_original||x[4],persona:x.persona_sugerida||x.persona||'manutencao'}}
function render(){const app=$('#app');app.replaceChildren();const card=el('section',undefined,'card');card.append(el('h2','Preparar um contato'),el('p','Busque na base e confira a pessoa antes de continuar a cadência.','muted'));const q=document.createElement('input');q.placeholder='Ex.: Carlos da Ambev';const b=el('button','Buscar');const out=el('div',undefined,'result');b.onclick=async()=>{out.replaceChildren(el('p','Buscando…'));try{const d=await api('/api/base?q='+encodeURIComponent(q.value));state.base=d.rows||d.values||[];out.replaceChildren(...state.base.slice(0,30).map(x=>{const c=normalize(x),r=el('button',`${c.contato||'Contato'} · ${c.empresa||'Empresa'}`);r.onclick=()=>contact(c);return r;}));}catch(e){out.replaceChildren(el('p',e.message,'warn'))}};card.append(q,b,out);app.append(card);const hist=el('section',undefined,'card');hist.append(el('h2','Histórico'));const hb=el('button','Atualizar histórico');const ho=el('div',undefined,'result');hb.onclick=async()=>{try{await loadHistory();ho.replaceChildren(el('p',`${Math.max(0,state.history.length-1)} evento(s) carregado(s).`))}catch(e){ho.replaceChildren(el('p',e.message,'warn'))}};hist.append(hb,ho);app.append(hist)}
function visionWidget(info){const box=el('div',undefined,'result'),input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';const out=el('div',undefined,'result'),b=el('button','Ler print com IA');b.onclick=async()=>{const f=input.files?.[0];if(!f)return out.replaceChildren(el('p','Escolha um print primeiro.','warn'));if(!confirm('O print será enviado à OpenAI pelo Make. Deseja continuar?'))return;const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f)});try{const d=await api('/api/vision',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image_base64:data,mime:f.type,consentimento:true})});out.replaceChildren(el('p',d.pergunta_identidade||'Confira os dados lidos.'),el('p',d.evidencia_empresa||'','muted'));if(d.texto_principal){const t=document.createElement('textarea');t.value=d.texto_principal;const use=el('button','Usar texto conferido como contexto');use.onclick=()=>{info.value=t.value};out.append(t,use)}for(const a of d.alertas||[])out.append(el('p',a,'warn'))}catch(e){out.replaceChildren(el('p',e.message,'warn'))}};box.append(el('label','Print para leitura inteligente'),input,b,out);return box}
function contact(c){const app=$('#app');app.replaceChildren();const card=el('section',undefined,'card');card.append(el('h2',`${c.contato} · ${c.empresa}`),el('p',c.cargo_original||'Cargo a conferir','muted'));const persona=document.createElement('select');Object.entries(fallbackQuestions).forEach(([k,v])=>persona.append(new Option(k,v)));persona.value=c.persona;const info=document.createElement('textarea');info.placeholder='Informação concreta sobre a planta, a operação ou o dia a dia do cliente.';const show=el('div',undefined,'result');const refresh=()=>{show.replaceChildren();const stage=stageFor(c),e=makeEmail(c,info.value.trim(),stage);if(hasResponse(c)){show.append(el('p','O prospect respondeu. A cadência está pausada até tratar essa resposta.','warn'));replyBox(show,c,stage);return}if(!e){show.append(el('p','As quatro etapas já foram enviadas. Deixe a apresentação disponível para um próximo contato.','muted'));return}show.append(el('h3',`E-mail ${stage} · ${e.subject}`),el('div',e.body,'email'));const made=el('button','Registrar e-mail criado');made.onclick=async()=>{await row(c,'email_criado',{etapa:stage,assunto:e.subject,texto:e.body});await loadHistory();refresh()};show.append(made);const sent=el('button','Registrar envio');sent.onclick=async()=>{await row(c,'email_enviado',{etapa:stage,assunto:e.subject,texto:e.body});await loadHistory();refresh()};show.append(sent)};const response=el('button','Registrar resposta do prospect');response.onclick=()=>{show.replaceChildren(el('h3','Resposta do prospect'));const t=document.createElement('textarea');t.placeholder='Cole a mensagem nova ou a transcrição do print.';const save=el('button','Guardar resposta');save.onclick=async()=>{if(!t.value.trim())return;await row(c,'resposta_recebida',{etapa:stageFor(c),texto:t.value,resposta:t.value});await loadHistory();refresh()};show.append(t,save)};const gen=el('button','Mostrar e-mail disponível');gen.onclick=()=>{if(!info.value.trim()){show.replaceChildren(el('p','O print não acrescentou informação relevante. Envie um print ou texto sobre a planta, a operação ou alguma atividade do dia a dia do cliente.','warn'));return}refresh()};card.append(el('label','Persona'),persona,visionWidget(info),el('label','Informação personalizada'),info,gen,response,show);app.append(card);refresh()}
function replyBox(parent,c,stage){const t=document.createElement('textarea');t.placeholder='Escreva a resposta depois de conferir o que o prospect respondeu.';const save=el('button','Registrar resposta preparada');save.onclick=async()=>{if(!t.value.trim())return;await row(c,'resposta_criada',{etapa:stage,texto:t.value});parent.append(el('p','Resposta registrada no histórico.','muted'))};parent.append(t,save)}
async function boot(){try{state.cadencia=await fetch('cadencia.json').then(r=>r.json());await loadHistory()}catch(e){console.warn(e)}$('#seller').value=state.seller;$('#saveSeller').onclick=()=>{state.seller=$('#seller').value.trim();if(!state.seller)return;localStorage.setItem('timwin.jph.seller',state.seller);$('#seller').closest('section').hidden=true;$('#app').hidden=false;render()};if(state.seller){$('#seller').closest('section').hidden=true;$('#app').hidden=false;render()}}
boot();

